name: SpringBoot CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup JAVA
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Ensure Maven wrapper is executable
        run: chmod +x ./mvnw

      - name: Build Application
        run: ./mvnw clean package

      - name: Build Docker Image
        run: docker build -t ci-cd .

    permissions:
      contents: read
      packages: write
                - name: login to GHCR
                  uses: docker/build-push-action@v3
                  with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
    
                - name: Push Docker Image
                  uses: docker/build-push-action@v3
                  with:
                      context: .
                      push: true
                      tags: ghcr.io/${{ github.repository_owner }}/ci-cd:latest
